# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3077019b268e02efd0ca65c4cfe1d13f2d0f3f707da2612884cec5565d84962cd93003a9c5ecc4b363e22c9ffc316f5193468c3a68dbe50294a88bca115c41b3

test:
  secret_key_base: 47919349bd0b22db5a04965d5570460db7ac02a0de70c7059714225aa3554646669e9c1a157f7bc44223302da60df5ccb8afc201102fc826e880c56f6debd1fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
